# Generated by Django 2.1 on 2019-07-01 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssiTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'Assign_teacher',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.IntegerField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(choices=[('CS', 'computer science'), ('M', 'mathematics'), ('ENG', 'english'), ('HND', 'hindi'), ('SCI', 'science')], max_length=10)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Div',
            fields=[
                ('d_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('division', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'class_div',
            },
        ),
        migrations.CreateModel(
            name='Klass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('total_student', models.IntegerField(default=0, null=True)),
            ],
            options={
                'db_table': 'klass_info',
            },
        ),
        migrations.CreateModel(
            name='SchoolUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dob', models.DateField(blank=True, null=True)),
                ('role', models.IntegerField()),
                ('profile_pic', models.CharField(default='', max_length=255)),
                ('gender', models.CharField(default='m', max_length=1)),
                ('address', models.CharField(default='', max_length=255)),
                ('s_name', models.CharField(blank=True, max_length=60, null=True)),
                ('f_name', models.CharField(blank=True, max_length=100, null=True)),
                ('m_nane', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_no', models.CharField(max_length=12, null=True)),
                ('user_auth', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_info',
            },
        ),
        migrations.CreateModel(
            name='StudAtt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_date', models.DateField(blank=True, null=True)),
                ('a_status', models.CharField(blank=True, max_length=10, null=True)),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Klass')),
                ('s_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='management.SchoolUser')),
            ],
            options={
                'db_table': 'student_att',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('div', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='management.Div')),
                ('klass', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='management.Klass')),
                ('s_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='management.SchoolUser')),
            ],
            options={
                'db_table': 'student_info',
            },
        ),
        migrations.CreateModel(
            name='StudentFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.IntegerField()),
                ('s_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='management.SchoolUser')),
            ],
            options={
                'db_table': 'fees',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('sub_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sub_name', models.CharField(max_length=100)),
                ('marks', models.IntegerField(null=True)),
                ('pass_marks', models.IntegerField(null=True)),
                ('s_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='management.SchoolUser')),
            ],
            options={
                'db_table': 'subject_info',
            },
        ),
        migrations.CreateModel(
            name='TeachAtt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_date', models.DateField(blank=True, null=True)),
                ('a_status', models.CharField(blank=True, max_length=10, null=True)),
                ('s_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='management.SchoolUser')),
            ],
            options={
                'db_table': 'teacher_att',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=30)),
                ('joined', models.DateField(verbose_name='Year-Month')),
                ('s_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='management.SchoolUser')),
            ],
            options={
                'db_table': 'teacher',
            },
        ),
        migrations.AddField(
            model_name='div',
            name='klass',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='management.Klass'),
        ),
        migrations.AddField(
            model_name='department',
            name='dept_head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Teacher'),
        ),
        migrations.AddField(
            model_name='department',
            name='s_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='management.SchoolUser'),
        ),
        migrations.AddField(
            model_name='department',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Subject'),
        ),
        migrations.AddField(
            model_name='assiteacher',
            name='div',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='management.Div'),
        ),
        migrations.AddField(
            model_name='assiteacher',
            name='klass',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='management.Klass'),
        ),
        migrations.AddField(
            model_name='assiteacher',
            name='s_id',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='management.SchoolUser'),
        ),
    ]
