# Generated by Django 2.1 on 2019-07-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20190701_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooluser',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
